name: Build and Test
on:
    push:
        branches:
            - master
    workflow_dispatch:
jobs:
    build_and_test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Install & Build
              run: yarn install && yarn build
